In [1]:
from openbb_terminal.sdk import openbb
from datetime import datetime
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
%matplotlib inline

Forecasting Toolkit is disabled. To use the Forecasting features please install the toolkit following the instructions here: https://my.openbb.co/app/sdk/installation

Portfolio Optimization Toolkit is disabled. To use the Optimization features please install the toolkit following the instructions here: https://my.openbb.co/app/sdk/installation

In [2]:
help(openbb.forex)

Help on ForexController in module openbb_terminal.core.sdk.controllers.forex_sdk_controller object:

class ForexController(openbb_terminal.core.sdk.models.forex_sdk_model.ForexRoot)
 |  Forex Module.
 |
 |  Submodules:
 |      `oanda`: Oanda Module
 |
 |  Attributes:
 |      `candle`: Show candle plot for fx data.
 |
 |      `fwd`: Gets forward rates from fxempire
 |
 |      `get_currency_list`: Load AV currency codes from a local file.
 |
 |      `load`: Load forex for two given symbols.
 |
 |      `quote`: Get forex quote.
 |
 |  Method resolution order:
 |      ForexController
 |      openbb_terminal.core.sdk.models.forex_sdk_model.ForexRoot
 |      openbb_terminal.core.sdk.sdk_helpers.Category
 |      builtins.object
 |
 |  Readonly properties defined here:
 |
 |  oanda
 |      Forex Oanda Submodule
 |
 |      Attributes:
 |          `calendar`: Request data of significant events calendar.
 |
 |          `calendar_chart`: View calendar of significant events.
 |
 |          `cancel`: Request cancellation of a pending order.
 |
 |          `cancel_chart`: Cancel a Pending Order.
 |
 |          `candles`: Request data for candle chart.
 |
 |          `candles_chart`: Show candle chart.
 |
 |          `close`: Close a trade.
 |
 |          `close_chart`: Close a trade.
 |
 |          `listorders`: Request the orders list from Oanda.
 |
 |          `listorders_chart`: List order history.
 |
 |          `openpositions`: Request information on open positions.
 |
 |          `openpositions_chart`: Get information about open positions.
 |
 |          `opentrades`: Request open trades data.
 |
 |          `opentrades_chart`: View open trades.
 |
 |          `order`: Request creation of buy/sell trade order.
 |
 |          `order_chart`: Create a buy/sell order.
 |
 |          `orderbook`: Request order book data for plotting.
 |
 |          `orderbook_chart`: Plot the orderbook for the instrument if Oanda provides one.
 |
 |          `pending`: Request information on pending orders.
 |
 |          `pending_chart`: Get information about pending orders.
 |
 |          `positionbook`: Request position book data for plotting.
 |
 |          `positionbook_chart`: Plot a position book for an instrument if Oanda provides one.
 |
 |          `price`: Request price for a forex pair.
 |
 |          `price_chart`: View price for loaded currency pair.
 |
 |          `summary`: Request Oanda account summary.
 |
 |          `summary_chart`: Print Oanda account summary.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from openbb_terminal.core.sdk.models.forex_sdk_model.ForexRoot:
 |
 |  __init__(self)
 |      Initialize the class
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from openbb_terminal.core.sdk.sdk_helpers.Category:
 |
 |  __getattribute__(self, name: str)
 |      We override the __getattribute__ method and wrap all callable
 |
 |
 |
 |      attributes with a wrapper that logs the call and the result.
 |
 |  __repr__(self)
 |      Return the representation of the class.
 |
 |  about(self)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from openbb_terminal.core.sdk.sdk_helpers.Category:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from openbb_terminal.core.sdk.sdk_helpers.Category:
 |
 |  __annotations__ = {'_location_path': <class 'str'>}

In [9]:
currency_pair = openbb.forex.load(
    from_symbol='USD',
    to_symbol='EUR',
    start_date = '2000-01-01',
    interval = '1week')

currency_pair.head(5)

               Open     High      Low    Close  Adj Close  Volume
date
2003-12-01  0.83098  0.83724  0.82028  0.82163    0.82163       0
2003-12-08  0.82183  0.82488  0.81261  0.82068    0.82068       0
2003-12-15  0.82055  0.82115  0.80373  0.80919    0.80919       0
2003-12-22  0.80926  0.80926  0.78914  0.80425    0.80425       0
2003-12-29  0.80425  0.80451  0.79058  0.79126    0.79126       0

In [10]:
weekly_atr = openbb.ta.atr(data = currency_pair, window = 4)
currency_pair = currency_pair.join(weekly_atr)

currency_pair.tail(1)

             Open     High      Low  Close  Adj Close  Volume    ATRe_4
date
2023-09-11  0.933  0.93358  0.92964  0.933      0.933       0  0.008791

In [11]:
openbb.forex.quote("EURUSD", source = "AlphaVantage")

                      Realtime Currency Exchange Rate
1. From_Currency Code                             USD
2. From_Currency Name            United States Dollar
3. To_Currency Code                               EUR
4. To_Currency Name                              Euro
5. Exchange Rate                           0.93060000
6. Last Refreshed                 2023-09-12 01:08:03
7. Time Zone                                      UTC
8. Bid Price                               0.93059000
9. Ask Price                               0.93063000

In [12]:
fwd_usdeur = openbb.forex.fwd('EUR', 'USD')

fwd_usdeur

                   Ask      Bid      Mid   Points
Expiration
Overnight      0.93075  0.93071  0.93073   -0.415
Tomorrow Next  0.93075  0.93071  0.93073   -0.415
Spot Next      0.93075  0.93071  0.93073   -0.415
One Week       0.93050  0.93045  0.93047   -3.020
Two Weeks      0.93020  0.93015  0.93017   -6.005
Three Weeks    0.92985  0.92980  0.92983   -9.470
One Month      0.92938  0.92933  0.92935  -14.225
Two Months     0.92808  0.92803  0.92806  -27.185
Three Months   0.92670  0.92664  0.92667  -41.035
Four Months    0.92461  0.92454  0.92457  -62.020
Five Months    0.92333  0.92326  0.92330  -74.780
Six Months     0.92206  0.92197  0.92201  -87.600
Seven Months   0.92055  0.92047  0.92051 -102.625
Eight Months   0.91926  0.91916  0.91921 -115.635
Nine Months    0.91791  0.91781  0.91786 -129.140
Ten Months     0.91650  0.91638  0.91644 -143.340
Eleven Months  0.91525  0.91512  0.91518 -155.920
One Year       0.91389  0.91374  0.91381 -169.620
Two Years      0.90094  0.90049  0.90071 -300.620

In [13]:
fwd_eurusd = openbb.forex.fwd('USD', 'EUR')

fwd_eurusd

                   Ask      Bid      Mid     Points
Expiration
Overnight      1.07454  1.07449  1.07451     0.4800
Tomorrow Next  1.07454  1.07449  1.07451     0.4800
Spot Next      1.07454  1.07449  1.07451     0.4800
One Week       1.07484  1.07478  1.07481     3.4400
Two Weeks      1.07518  1.07512  1.07515     6.8000
Three Weeks    1.07556  1.07551  1.07554    10.7000
One Month      1.07610  1.07604  1.07607    16.0155
Two Months     1.07759  1.07750  1.07754    30.7500
Three Months   1.07914  1.07907  1.07910    46.3840
Four Months    1.08160  1.08148  1.08154    70.7500
Five Months    1.08313  1.08298  1.08306    85.9000
Six Months     1.08463  1.08448  1.08456   100.9000
Seven Months   1.08645  1.08620  1.08633   118.6000
Eight Months   1.08797  1.08772  1.08784   133.8000
Nine Months    1.08958  1.08933  1.08946   149.9000
Ten Months     1.09125  1.09100  1.09112   166.6000
Eleven Months  1.09277  1.09252  1.09265   181.8000
One Year       1.09439  1.09414  1.09427   198.0000
Two Years      1.11037  1.10982  1.11010   356.3000
Three Years    1.12737  1.12662  1.12700   525.3000
Four Years     1.13164  1.12959  1.13062   561.5000
Five Years     1.14564  1.14259  1.14412   696.5000
Six Years      1.16549  1.16394  1.16471   902.5000
Seven Years    1.17869  1.17664  1.17767  1032.0000
Ten Years      1.21799  1.21294  1.21547  1410.0000

In [14]:
fwd_eurjpy = openbb.forex.fwd('JPY', 'EUR')
fwd_pairs = fwd_eurjpy.join(fwd_usdeur, on = ['Expiration'], lsuffix = ' EUR/JPY', rsuffix=' USD/EUR')

fwd_pairs

,Ask EUR/JPY,Bid EUR/JPY,Mid EUR/JPY,Points EUR/JPY,Ask USD/EUR,Bid USD/EUR,Mid USD/EUR,Points USD/EUR
Expiration,,,,,,,,
Overnight,157.561,157.543,157.552,-1.7350,0.93075,0.93071,0.93073,-0.415
Tomorrow Next,157.561,157.543,157.552,-1.7550,0.93075,0.93071,0.93073,-0.415
Spot Next,157.561,157.543,157.552,-1.7550,0.93075,0.93071,0.93073,-0.415
One Week,157.560,157.542,157.551,-12.2000,0.93050,0.93045,0.93047,-3.020
Two Weeks,157.559,157.541,157.550,-24.6000,0.93020,0.93015,0.93017,-6.005
Three Weeks,157.557,157.539,157.548,-37.7300,0.92985,0.92980,0.92983,-9.470
One Month,157.555,157.537,157.546,-57.1825,0.92938,0.92933,0.92935,-14.225
Two Months,157.550,157.532,157.541,-108.0150,0.92808,0.92803,0.92806,-27.185
Three Months,157.545,157.527,157.536,-160.5030,0.92670,0.92664,0.92667,-41.035
Four Months,157.539,157.521,157.530,-218.5200,0.92461,0.92454,0.92457,-62.020
Five Months,157.534,157.516,157.525,-268.2250,0.92333,0.92326,0.92330,-74.780
Six Months,157.529,157.511,157.520,-318.2150,0.92206,0.92197,0.92201,-87.600
Seven Months,157.524,157.506,157.515,-371.6300,0.92055,0.92047,0.92051,-102.625
Eight Months,157.519,157.501,157.510,-419.8650,0.91926,0.91916,0.91921,-115.635
Nine Months,157.514,157.496,157.505,-470.4500,0.91791,0.91781,0.91786,-129.140
Ten Months,157.509,157.491,157.500,-520.6300,0.91650,0.91638,0.91644,-143.340
Eleven Months,157.505,157.486,157.495,-565.1450,0.91525,0.91512,0.91518,-155.920
One Year,157.500,157.481,157.490,-616.9200,0.91389,0.91374,0.91381,-169.620
Two Years,157.454,157.434,157.444,-1080.5600,0.90094,0.90049,0.90071,-300.620